CREATE TABLE "candidato" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "sobrenome" varchar(50) NOT NULL,
  "data_nascimento" date NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "cpf" varchar(11) UNIQUE NOT NULL,
  "descricao" text NOT NULL,
  "senha" varchar(30) NOT NULL,
  "id_endereco" int NOT NULL
);

CREATE TABLE "empresa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "cnpj" varchar(14) UNIQUE NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "descricao" text NOT NULL,
  "senha" varchar(30) NOT NULL,
  "id_endereco" int NOT NULL
);

CREATE TABLE "vaga" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "descricao" text NOT NULL,
  "id_endereco" int NOT NULL,
  "id_empresa" int NOT NULL,
  "ativa" bool NOT NULL DEFAULT true
);

CREATE TABLE "competencia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "candidato_competencia" (
  "id_candidato" int NOT NULL,
  "id_competencia" int NOT NULL,
  PRIMARY KEY ("id_candidato", "id_competencia")
);

CREATE TABLE "vaga_competencia" (
  "id_vaga" int NOT NULL,
  "id_competencia" int NOT NULL,
  PRIMARY KEY ("id_vaga", "id_competencia")
);

CREATE TABLE "endereco" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cep" varchar(8) NOT NULL,
  "cidade" varchar(30) NOT NULL,
  "estado" varchar(30) NOT NULL,
  "pais" varchar(30) NOT NULL
);

CREATE TABLE "interacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_candidato" int NOT NULL,
  "id_vaga" int NOT NULL,
  "origem" char(1) NOT NULL,
  "tipo" char(1) NOT NULL
);

CREATE TABLE "match" (
  "id_vaga" int NOT NULL,
  "id_candidato" int NOT NULL,
  PRIMARY KEY ("id_vaga", "id_candidato")
);

CREATE UNIQUE INDEX ON "interacao" ("id_candidato", "id_vaga", "origem");

COMMENT ON COLUMN "interacao"."origem" IS 'C = candidato, E = empresa';

COMMENT ON COLUMN "interacao"."tipo" IS 'L = like, D = deslike';

ALTER TABLE "candidato" ADD FOREIGN KEY ("id_endereco") REFERENCES "endereco" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "empresa" ADD FOREIGN KEY ("id_endereco") REFERENCES "endereco" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vaga" ADD FOREIGN KEY ("id_endereco") REFERENCES "endereco" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vaga" ADD FOREIGN KEY ("id_empresa") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "candidato_competencia" ADD FOREIGN KEY ("id_candidato") REFERENCES "candidato" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "candidato_competencia" ADD FOREIGN KEY ("id_competencia") REFERENCES "competencia" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vaga_competencia" ADD FOREIGN KEY ("id_vaga") REFERENCES "vaga" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vaga_competencia" ADD FOREIGN KEY ("id_competencia") REFERENCES "competencia" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "interacao" ADD FOREIGN KEY ("id_candidato") REFERENCES "candidato" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "interacao" ADD FOREIGN KEY ("id_vaga") REFERENCES "vaga" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "match" ADD FOREIGN KEY ("id_vaga") REFERENCES "vaga" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "match" ADD FOREIGN KEY ("id_candidato") REFERENCES "candidato" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "interacao" ADD CONSTRAINT chk_origem CHECK (origem IN ('C', 'E'));
ALTER TABLE "interacao" ADD CONSTRAINT chk_tipo CHECK (tipo IN ('L', 'D'));